trihouse_interfaces/TaskContext task_context
string pickup_location_id
string dropoff_location_id
string destination_code
geometry_msgs/PoseStamped pickup_pose
geometry_msgs/PoseStamped dropoff_pose
uint8 priority
bool requires_precise_stop
uint8 MODE_TRANSPORT=0
uint8 MODE_RETURN_TO_WAIT=1
uint8 MODE_RETURN_TO_CHARGE=2
uint8 MODE_RMF_NAVIGATION=3
uint8 mode
---
uint16 CODE_OK=0
uint16 CODE_REJECTED=1
uint16 CODE_CANCELED=2
uint16 CODE_NAVIGATION_FAILED=3
uint16 CODE_DOCK_FAILED=4
uint16 CODE_HANDOVER_FAILED=5

bool success
uint16 code
string message
builtin_interfaces/Time completed_at
---
uint8 PHASE_ACCEPTED=0
uint8 PHASE_NAVIGATING=1
uint8 PHASE_DOCKING=2
uint8 PHASE_HANDOVER=3
uint8 PHASE_COMPLETED=4

uint8 phase
float32 progress
geometry_msgs/PoseStamped current_pose
string detail
