uint8 SKILL_BACKUP=0
uint8 SKILL_REROUTE_LEFT=1
uint8 SKILL_REROUTE_RIGHT=2
uint8 SKILL_WAIT_REOBSERVE=3
uint8 SKILL_REJOIN=4

string command_id
string proposal_id
string proposal_sha256
string approval_id
string approval_worker_id
string device_id
string map_name
string map_revision
string recovery_episode_uuid
uint32 step_no
uint8 selected_skill_id
string selected_skill_name
geometry_msgs/Vector3 canonical_coord
bool has_map_target
geometry_msgs/PoseStamped map_target
---
uint16 CODE_OK=0
uint16 CODE_REJECTED=1
uint16 CODE_CANCELED=2
uint16 CODE_NAV2_FAILED=3
uint16 CODE_SAFETY_VETO=4

bool success
uint16 code
string status
string detail
geometry_msgs/PoseStamped pre_pose
geometry_msgs/PoseStamped post_pose
float32 clearance_before_m
float32 clearance_after_m
float32 elapsed_seconds
bool safety_intervened
bool terminal
---
uint8 PHASE_ACCEPTED=0
uint8 PHASE_SAFETY_CHECK=1
uint8 PHASE_EXECUTING=2
uint8 PHASE_OBSERVING=3

uint8 phase
string detail
geometry_msgs/PoseStamped current_pose
float32 minimum_clearance_m
