ARG BASE_IMAGE=nvcr.io/nvidia/pytorch:26.07-py3
FROM ${BASE_IMAGE}

WORKDIR /opt/trihouse
ENV PYTHONPATH=/opt/trihouse
COPY vision_ai vision_ai

ENTRYPOINT ["python", "-m", "vision_ai.models.recovery.trainer.offline_train"]
